<?php
  echo "<div id='btn-back-admin' align='center' onclick='form_angkatan(null)'>";
  echo "  <i class='fa fa-arrow-left'></i>";
  echo "</div>";
  echo "<div class='form' style='margin-top: 4vh'>";
  echo "  <div class='main-form'>";
  echo "    <form action='anggota/add_angkatan'>";
  echo "      <h4><b>Form Angkatan</b></h4>";
  echo "      <br>";
  echo "      <div class='row'>";
  echo "        <div class='col-lg-3'>";
  echo "          <h5> Angkatan </h5>";
  echo "          <input type='number' name='angkatan' placeholder='Angkatan'>";
  echo "        </div>";
  echo "      </div>";
  echo "      <br>";
  echo "      <div class='row'>";
  echo "        <div class='col-lg-3'>";
  echo "          <h5> Masa Jabatan </h5>";
  echo "          <input type='number' name='masa-jabatan' placeholder='Masa Jabatan'>";
  echo "        </div>";
  echo "      </div>";
  echo "      <br>";
  echo "      <div class='row'>";
  echo "        <div class='col-lg-6'>";
  echo "          <h5> Visi Angkatan</h5>";
  echo "          <textarea rows='10' placeholder='Kosongkan bila tidak ada.' name='visi'></textarea>";
  echo "        </div>";
  echo "        <div class='col-lg-6'>";
  echo "          <h5> Misi Angkatan</h5>";
  echo "          <textarea rows='10' placeholder='Kosongkan bila tidak ada.' name='misi'></textarea>";
  echo "        </div>";
  echo "      </div>";
  echo "      <br>";
  echo "      <br>";
  echo "      <div class='row'>";
  echo "        <div class='col-lg-2 col-lg-offset-8'><input type='reset' value='Cancel'></div>";
  echo "        <div class='col-lg-2'><input type='submit' value='Submit'></div>";
  echo "      </div>";
  echo "    </form>";
  echo "  </div>";
  echo "</div>";
?>